os: Visual Studio 2017
version: 3.0.{build}
configuration: Release
pull_requests:
  do_not_increment_build_number: true
init:
- ps: $Env:LABEL = $Env:APPVEYOR_BUILD_NUMBER
- ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))
build:
  verbosity: minimal
  publish_nuget: true
build_script:
- dotnet restore -v Minimal
- dotnet build -c %CONFIGURATION%
- dotnet pack -c %CONFIGURATION% .\src\TinyPng\TinyPNG.csproj -o .\artifacts 
artifacts:
- path: .\src\TinyPng\artifacts\**\*.*
before_test:
- cmd: choco install opencover.portable
test_script:
- cmd: pushd
- cmd: cd .\tests\TinyPng.Tests\ 
- cmd: opencover.console -target:"dotnet.exe" -targetargs:"test -c %CONFIGURATION% --no-build" -register:user -filter:"+[*]* -[xunit*]*" -output:"../../coverage.xml" -log:All -oldstyle -skipautoprops
after_test:
- "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- pip install codecov
- cd ../..
- codecov -f "coverage.xml" -X gcov
deploy:
- provider: NuGet
  api_key:
    secure: Gerln5x/jQ3CsCjXe76zQuP2Rjh12sKBH2wj88LIpt1IQym1+6MlFVWmvx5j+KSw
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: release
